# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Color Deck' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Color Deck
pod 'DOFavoriteButton'

  target 'Color DeckTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Color DeckUITests' do
    # Pods for testing
  end

end
